### ISSUE TITLE
Decorator for auth

### ISSUE THREAD

**Issue by yograterol** [echevemaster/fedora-college#20]
Add a auth decorator for functions.

**Comment by hammadhaleem** [comment]
I am using an authentication function which serves same feature.

https://github.com/hammadhaleem/fedora-college/blob/develop/fedora_college/modules/content/views.py#L20

**Comment by yograterol** [comment]
Yes I know, but a decorator it's more functional.

**Comment by hammadhaleem** [comment]
Added decorators :) using default for now.

from flask_fas_openid import fas_login_required
@fas_login_required.

Thanks for point this out.
