### ISSUE TITLE
Blueprint prefix

### ISSUE THREAD

**Issue by yograterol** [echevemaster/fedora-college#21]
With blueprint prefix we can miss the prefix in all routes definition. (http://flask.pocoo.org/docs/api/#flask.Blueprint)

https://github.com/echevemaster/fedora-college/blob/develop/fedora_college/modules/api/views.py#L14

This:

``` python
bundle = Blueprint('api', __name__)
```

can be:

``` python
bundle = Blueprint('api', __name__, url_prefix='/api/')
```

**Comment by hammadhaleem** [comment]
Added in the latest commit, but not yet created a merge request.

https://github.com/hammadhaleem/fedora-college/commit/56cde34bae474cc335abab857d3753977a7625fe

**Comment by yograterol** [comment]
@hammadhaleem :) thanks!

**Comment by hammadhaleem** [comment]
You are most welcome :)
