### ISSUE TITLE
Don't send large pull requests

### ISSUE THREAD

**Issue by yograterol** [echevemaster/fedora-college#24]
In my opinion don't should send large pull request, because becomes difficult the review.

**Comment by hammadhaleem** [comment]
Yeah, this time things got accumulated :)

**Comment by yograterol** [comment]
Don't worry, but for the next time send a pull request per feature.

**Comment by hammadhaleem** [comment]
Sure.

On Mon, Aug 11, 2014 at 8:18 PM, Yohan Graterol notifications@github.com
wrote:

> Don't worry, but for the next time send a pull request per feature.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/echevemaster/fedora-college/issues/24#issuecomment-51790005
> .

## 

Regards
Hammad Haleem
