### ISSUE TITLE
Possible structure of Models.

### ISSUE THREAD

**Issue by hammadhaleem** [echevemaster/fedora-college#7]
Hello,

I have prepared an ER diagram for possible structure of the models. I did write the code, and is currently commented. Open for discussions

![desktop](https://f.cloud.github.com/assets/934032/2368379/065d68b6-a7a5-11e3-9e43-4800216235dd.png)

Present in the fedora_college/core/models.py file.

**Comment by yograterol** [comment]
Not any fields string type should be String(255).

Tags is must a relation in a intermediate table

**Comment by hammadhaleem** [comment]
@yograterol  corrected that. Added a table linking tags with content. But still left this column to show tags without much processing.
